language: scala
scala:
  - "2.11.8"
jdk:
  - "oraclejdk8"
script:
  - sbt clean coverage test
  - sbt coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: required
services:
  - postgresql
addons:
  postgresql: "9.3"
before_install:
  - sudo apt-get update
  - sudo apt-get install skytools3-ticker postgresql-9.3-pgq3
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.3
  - psql -U postgres < /usr/share/postgresql/9.3/contrib/pgq.sql
  - pgqd --ini > ticker.ini
  - mkdir ~/log/ ~/pid/
  - pgqd ticker.ini -v -d
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
